name: AAOS CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Tests
      run: |
        docker compose up -d --build
        sleep 15
        docker compose exec -T python-worker python -m pytest test_auth.py
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker Compose
      run: |
        docker compose build
